CREATE TABLE property	(

	link VARCHAR(255) DEFAULT NULL,
	html TEXT DEFAULT NULL,
	address VARCHAR(255) DEFAULT NULL,
	price INT DEFAULT NULL,
	property_type VARCHAR(50) DEFAULT NULL,
	picture_count INT DEFAULT NULL,
	bedroom_type VARCHAR(50) DEFAULT NULL,
	couples INT DEFAULT NULL,
	total_residents INT DEFAULT NULL, 
	owner_occupied INT DEFAULT NULL

	PRIMARY KEY(link)

) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;